### ISSUE TITLE
Update compability for usb_device 3.x.x

### ISSUE THREAD

**Issue by SpamixOfficial** [ithinuel/usbd-picotool-reset#2]
Hello!

It seems like usb_device 3.x.x broke compability with this library! I really appreciate the library, but I really need to use it for usb_device 3.x.x. 

If you could update the examples and the types that are used that would be great! 

Thanks
// Spamix

**Comment by SpamixOfficial** [comment]
okay so #3 should fix this

**Comment by ithinuel** [comment]
https://crates.io/crates/usbd-picotool-reset 0.3 published 🎉

**Comment by SpamixOfficial** [comment]
> https://crates.io/crates/usbd-picotool-reset 0.3 published 🎉 

🎉🎉🎉
